### ISSUE TITLE
Dressing Room with ElvUI Skin shows two Outfit dropdowns

### ISSUE THREAD

**Issue by Beet4** [SLOKnightfall/BetterWardrobe#276]
No issues if I only have Better Wardrobe enabled. But when I enable Better Wardrobe + ElvUI (no other addons) two dropdown lists for outfits in the Dressing Room window is shown. One is outside of the frame itself. It seems like the one outside of the frame is the standard Blizzard one and the one at the top inside the frame is Better Wardrobes dropdown menu as that one shows the extended saved sets as well while the other does not.

![image](https://user-images.githubusercontent.com/38279393/185767377-77ce8fbc-09f7-416a-b16f-11688c7a3f75.png)

If I switch to the smaller window they are on top of eachother:
![image](https://user-images.githubusercontent.com/38279393/185767396-5e1920ee-32cc-42d6-8db4-1f15c0d26c88.png)

**Comment by SLOKnightfall** [comment]
Issue has been fixed

**Comment by Beet4** [comment]
Hi! Thanks, however it seems to still show up for me on 4.1.1:
![image](https://user-images.githubusercontent.com/38279393/198721005-ae6eb17d-d427-49d5-8e93-2a56d0352d13.png)

Also now only the left one outside of the frame is now usable, when I click a transmog in the "normal" dropdown menu nothing happens.

It also broke the dropdown menu in the Transmogrify-window, nothing happens when I click a saved transmog there either.

**Comment by SLOKnightfall** [comment]
Should be actually fixed in the 4.1.3 release
